language: python
python: 2.7

services:
  - docker

env:
  - TOX_ENV=py27

git:
  submodules: false

before_install:
  - git submodule update --init --recursive
  - pip install ansible
  - export BIOBLEND_GALAXY_API_KEY=admin
  - export BIOBLEND_GALAXY_URL=http://localhost:8080

script:
  - ansible-playbook -i "localhost," -c local build_images.yml
  - docker run -d -p 8080:80 docker_ansible_14.04
