FROM ubuntu:{{ ubuntu_version  }}

# ==> Specify playbook filename;      default = "playbook.yml"
ENV PLAYBOOK      ansible-artimed/galaxy.yml

# ==> Specify inventory filename;     default = "/etc/ansible/hosts"
ENV INVENTORY     inventory.yml

COPY ansible-playbook-wrapper /usr/local/bin/

RUN  DEBIAN_FRONTEND=noninteractive  apt-get update   && \
              echo "===> Updating TLS certificates..."         && \
              apt-get install -y --no-install-recommends openssl \
              ca-certificates python-dev python-pip build-essential && \
              pip install ansible


# ==> Executing Ansible (with a simple wrapper)...
ONBUILD  RUN  DEBIAN_FRONTEND=noninteractive  apt-get update   && \
              echo "===> Updating TLS certificates..."         && \
              apt-get install -y --no-install-recommends openssl \
              ca-certificates 

ONBUILD  WORKDIR  /tmp
ONBUILD  COPY  .  /tmp
ONBUILD  RUN  \
              echo "===> Diagnosis: host information..."  && \
              ansible -c local -m setup all

RUN ansible-playbook-wrapper

ENTRYPOINT /usr/bin/python /usr/bin/supervisord -c /etc/supervisor/supervisord.conf --nodaemon
